### ISSUE TITLE
Plugin incompatible with new Logstash version 2.0

### ISSUE THREAD

**Issue by fstradiotti** [awslabs/logstash-output-amazon_es#11]
New Logstash version has been released yesterday and it looks like this plugin is incompatible with it. 
When trying to install with the usual method of 'bin/plugin install..." I get the following multiple errors:

```
Validating logstash-output-amazon_es
Installing logstash-output-amazon_es
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.0.0)

  In Gemfile:
    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.0.2) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.0.2) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java
```

**Comment by MarcFowler** [comment]
+1 Same problem for me, I don't know how to fix it though unfortunately!

**Comment by MarcFowler** [comment]
I can confirm I'm on Java 1.8.x, and that rolling back to Logstash 1.5.x allows the installation of this with no problem. I don't know if this is a wider issue with other plugins too?

**Comment by csakoda** [comment]
Seeing the same trying to integrate the plugin into the `logstash:2` docker image

**Comment by malpani** [comment]
I have updated dependencies to work with Logstash 2.0 but not done extensive testing. From the looks of it this plugin should be forward compatible with 2.0 as well

**Comment by csakoda** [comment]
Many thanks!
