### ISSUE TITLE
How do I inspect document_level_metrics?

### ISSUE THREAD

**Issue by nhnicwaller** [awslabs/logstash-output-amazon_es#110]
This plugin allocates [two metric namespaces](https://github.com/awslabs/logstash-output-amazon_es/blob/84b811f59beaf707fd27805343203a69b3532f50/lib/logstash/outputs/amazon_es/common.rb#L27): `:bulk_requests` and `:documents` (saved as `@bulk_request_metrics` and `@document_level_metrics`, respectively) and increments several counters in those namespaces. I'm particularly interested in the `:non_retryable_failures` metric, but I'm not sure how to access it. I took a look at the [Logstash Monitoring APIs](https://www.elastic.co/guide/en/logstash/5.6/monitoring.html) but didn't see anything about accessing custom or namespaced metrics.

Can these metrics be inspected over the Logstash HTTP monitoring API? If not, what other way can they be sampled?

**Comment by AustinTag** [comment]
You can get this info with the "_node/stats" API. It will be under "pipelines.plugins.outputs" under the output for the amazon es plugin. Example:


{
            "id": "bab6389c5dc5e98eac8544298d6bcf2341cdd511e2f861c0c16c1918a7ef94a0",
            "events": {
              "in": 4,
              "out": 4,
              "duration_in_millis": 174
            },
            "documents": {
              "successes": 4
            },
            "bulk_requests": {
              "responses": {
                "200": 4
              },
              "successes": 4
            },
            "name": "amazon_es"
}
