### ISSUE TITLE
6.4.x causing continuous calls to AWS Metadata

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [awslabs/logstash-output-amazon_es#117]
## Description
Upgrading from from `logstash-output-amazon_es` `6.0.0` to `6.4.0` we started to experience 2 calls/second to the AWS Metadata service to obtain credentials from AWS instead of 2 calls every 10/15 minutes.

We tried to compile and use version `6.4.1` of `logstash-output-amazon_es` but the issue persisted and probably is not connected to bugs #105 and #101 

## Workaround
Going back to `6.0.0` obviously solve the issue.

## Info
logstash-output-amazon_es: `6.4.0`/`6.4.1`
Logstash version: `6.5.1/6.4.1`

**Comment by crisidev** [comment]
The PR looks good. We will try to release it between the end of this week, beginning of next.
