### ISSUE TITLE
413 - request too large

### ISSUE THREAD

**Issue by lifeofguenter** [awslabs/logstash-output-amazon_es#119]
Analogue to: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/785

Ideally this would be configurable.

**Comment by crisidev** [comment]
If I get this right we can make this configurable.

https://github.com/awslabs/logstash-output-amazon_es/blob/be664634ee36d01351970dd212508fbcbd4fbaf4/lib/logstash/outputs/amazon_es/http_client.rb#L24

There is a gotcha anyway here: the number can't be bigger than 100M, which is the max batch side accepted by ES. Increasing this will also increase heap memory usage, especially when multiple threads are involved.

We can work on a PR to make this configurable, just be careful with your memory :)

**Comment by phillycheeze** [comment]
I know this a year old now, but wanted to bring it up again as we are running into the same issue. The elasticsearch output plugin still has the issue mentioned above.

Currently the only way to make this work is to patch the underlying http_client.rb and set it to your own value (under 10MB). If anyone has other workarounds, would love to hear those as well!

**Comment by lifeofguenter** [comment]
I believe this has already been fixed in the latest versions:

https://github.com/awslabs/logstash-output-amazon_es/commit/ae5c9bd164dae7be2a8f2473e8e36bd77aaf3505

closing this ticket :)
