### ISSUE TITLE
Publish 6.4.1 release

### ISSUE THREAD

**Issue by eriksw** [awslabs/logstash-output-amazon_es#120]
As mentioned in a comment on #105 dated Dec 14, 2018 **(73 days ago as of the creation of this issue)**, 6.4.1 has not been uploaded to https://rubygems.org/gems/logstash-output-amazon_es

The fixes in 6.4.1 are **required** for this plugin to work with the most recent version of Elasticsearch offered by AWS Elasticsearch Service. We suffered a downtime of our logging infrastructure because the currently-published version of this plugin was unable to apply the updated ES6-compatible mapping, causing event indexing to fail after we upgraded to ES6. This was not resolved until we manually built a 6.4.1 gem ourselves and installed it. 😡

Please expeditiously update the published version so that when people run `logstash-plugin install logstash-output-amazon_es` they get a version that actually works with the current AWS Elasticsearch Service.

**Comment by cbittencourt** [comment]
@eriksw Can you describe or reference documentation on the steps needed to install the manually built gem? I'm facing the same issue but cannot find logstash's documentation on installing a plugin from the filesystem.

**Comment by cbittencourt** [comment]
In case anyone is looking for instructions on getting a locally built version installed: https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#installing-local-plugins

**Comment by crisidev** [comment]
We have released version 6.4.1 yesterday. Sorry for the delay and thanks a lot for your patience folks. I am resolving this issue.

Rubygem: https://rubygems.org/gems/logstash-output-amazon_es/versions/6.4.1-x86_64-linux
