### ISSUE TITLE
Does this plugin support aws_sigv4?

### ISSUE THREAD

**Issue by weizhu-us** [awslabs/logstash-output-amazon_es#132]
I can't find any code in the repo which signs the request. Can someone please confirm?

**Comment by crisidev** [comment]
Yes, this plugin supports sigv4 using a Ruby gem called manticore

**Comment by weizhu-us** [comment]
I just tested and getting the error like this:
[2019-10-11T00:24:20,908][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://search-XXXXX.us-east-1.es.amazonaws.com:443/, :path=>"/"}
[2019-10-11T00:24:20,914][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://search-XXXXX.us-east-1.es.amazonaws.com:443/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '403' contacting Elasticsearch at URL 'https://search-XXXX.us-east-1.es.amazonaws.com:443/'"}
We setup Instance profile credentials delivered through the Amazon EC2 metadata service and I wrote a python script using boto and it can connect to the es suceesfully

  url = "https://search-XXXXX.us-east-1.es.amazonaws.com:443/"
    headers = {'content-type': 'application/json'}

    # Get auth
    boto_session = session.Session()
    credentials = boto_session.get_credentials()
    region = 'us-east-1'
    service = 'es'
    auth = AWSV4Sign(credentials, region, service)

    try:

        response = requests.get(url, auth=auth, headers=headers, timeout=1.0)
        json = response.json()
        print(json)
    except Exception as exception:
        LOG.exception("Could not connect.")

Anything I can try to resolve the issue?

**Comment by AustinTag** [comment]
Can you verify a few things?

1. Which version of this plugin are you using?
2. What is the policy on the IAM role that you attached to your EC2?
3. What versions of Logstash and ES are you running?

**Comment by weizhu-us** [comment]
logstash 6.5.4
plugin-version: 6.4.2
ES version: 7.1
policy: 

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "es:ESHttpGet",
        "es:ESHttpDelete",
        "es:ESHttpPut",
        "es:ESHttpPost"
      ],
      "Resource": [
        "arn:aws:es:us-east-1:XXXXXXXX:domain/visibility-es*"
      ]
    }
  ]
}

If I use python boto, I can connect to the es with no problem. 
Thanks for you help.

**Comment by AustinTag** [comment]
Your EC2 policy does not have the access that it needs. Try allowing action "es:*" and see if that fixes your problem. I will investigate as to the minimal privileges needed, but you should be able to  fix your issue by allowing action "es:*"

**Comment by weizhu-us** [comment]
looks like it need all of those? 

[:get, :put, :post, :delete, :patch, :head].each do |method|

For health check, it needs :head

**Comment by AustinTag** [comment]
Correct. And your policy does not seem to have patch or head. Were you able to test out a policy with the required access?

**Comment by weizhu-us** [comment]
I need to work with security team to add more permission. I will keep you updated.Thanks

**Comment by weizhu-us** [comment]
I can find permission for patch here:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html

**Comment by AustinTag** [comment]
The following access list works for me:

"Action": [
                "es:ESHttpHead",
                "es:ESHttpPost",
                "es:ESHttpGet",
                "es:ESHttpDelete",
                "es:ESHttpPut"
            ]


Can you try that?

**Comment by weizhu-us** [comment]
Yes. it worked after new permission is added. Thanks so much for you help!
