### ISSUE TITLE
Switch off console logs

### ISSUE THREAD

**Issue by arun-a-nayagam** [awslabs/logstash-output-amazon_es#139]
Hi,
I am using a docker logstash and amazon_es output plugin
It's able to write to AWS elasticsearch fine, but it also writes the messages to console, that results in a lot of I/O, resulting in the machine becoming unresponsive.
How do I disable console logs?

Thanks,
Arun

**Comment by AustinTag** [comment]
Hi, can you post your logstash configuration file here?

**Comment by arun-a-nayagam** [comment]
Hi @AustinTag , 
Thanks for responding. Apologies, I did find a resolution but forgot to update here.
It was the default /usr/share/logstash/pipeline/logstash.conf that was writing to console.
I overwrote it with a conf file of my own, that resolved the issue.

Thanks,
Arun
