### ISSUE TITLE
Please publish a release compatible with (and tested with) AWS ES 7.1

### ISSUE THREAD

**Issue by TomJohnson-Syncbak** [awslabs/logstash-output-amazon_es#142]
There are currently 6.0, 6.4, 6.x, pre-6.x, and 1.0 branches, as well as a master branch.

The compatibility table states:

| logstash-output-amazon_es | Logstash |
| ------------------------------------- | ------------ |
| 6.0.0 | <6.0.0 |
| 6.4.0 | >6.0.0 |

This omits some useful information including:

- What Elasticsearch version(s) were each of these tested with?  Please add a column for this information.
- What versions are compatible with Elasticsearch 6.5, 6.6, 6.7, 6.8, and 7.1?  Please add rows as needed for this information.

Now that AWS offers Elasticsearch version 7.1 as a choice when creating or upgrading a domain, ideally there would be a 7.1 or 7.X branch so that someone using Logstash with AWS Elasticsearch could easily clone a compatible version of the plugin.

**Comment by AustinTag** [comment]
After doing some initial testing, I can verify that the "master" branch (also the version in the logstash repository to download via the logstash plugin manager) is compatible with ES versions 6.5, 6.7, 6.8, and 7.1 (Amazon Elasticsearch does not currently offer ES version 6.6). I will update the readme after doing more extensive testing.

**Comment by TomJohnson-Syncbak** [comment]
Would you consider creating a branch and/or a tag, rather than relying on "master"?

**Comment by AustinTag** [comment]
The version of this plugin does not correspond to an ES version (they just happen to be in the same numbering space right now). The "master" branch is for the most up-to-date plugin that lives in the Logstash repository. What is the branch/tag that you had in mind?

**Comment by TomJohnson-Syncbak** [comment]
Because there are existing branches and tags that seem to correspond to something approximating ES versions, I thought that might be a useful convention to follow with something that is advertised as tested with ES 7.1.  So, I thought a branch of 7.1 or a tag of v7.1.x might be appropriate.

It is entirely possible that I misunderstood the meaning of the branches and tags that already existed.   If they do not correspond to either an ES version or a Logstash version, I can understand why it might be misleading to create a new branch or tag.

**Comment by AustinTag** [comment]
Ah, I can see why there might be some confusion since all of the Logstash, ES, and this plugin versions are in the 6.0-7.X space. There has also been some confusing naming on these branches, but they are mostly named for the Logstash version they are meant to support. In addition, most of these branches were created for making a new version of the plugin, and then merged into master and left alone. So they should be cleaned up.
