### ISSUE TITLE
Support for setting the doc type and _id?

### ISSUE THREAD

**Issue by mkadin** [awslabs/logstash-output-amazon_es#145]
One of the main reasons we're using Logstash instead of AWS's firehose is to be able to control the _id of the document that's generated.  We also set different doc types for different kinesis streams.

Is it possible to set the _id with this plugin like you can with the normal elasticsearch plugin?  Here's our existing configuration, I'm wondering if it's possible to reproduce it using this plugin.

```
output {
      elasticsearch {
          index => "some_index_name"
          document_type => "some_doc_type"
          document_id => "%{[download][uuid]}"
      }
}
```

**Comment by ercpereda** [comment]
https://github.com/awslabs/logstash-output-amazon_es/blob/84b811f59beaf707fd27805343203a69b3532f50/lib/logstash/outputs/amazon_es/common_configs.rb#L60

**Comment by AustinTag** [comment]
It looks like your question has been answered here. Please re-open if you have any issues.
