### ISSUE TITLE
Is it possible to use the Logstash plugin with AWS Cognito?

### ISSUE THREAD

**Issue by r3kzi** [awslabs/logstash-output-amazon_es#157]
If i understood correctly you can specify AWS Access and Secret Keys for pushing logs to AWS ES.

What if i enable AWS Cognito for authentication?

I would think the specified Access and Secret keys only pass the [Domain access policy](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html#es-ac-types-resource).

**Comment by helongfei-myob** [comment]
The same issues, is it possible to use Logstash plugin with AWS Cognito

**Comment by rlewkowicz** [comment]
@AustinTag 

I'm just picking anyone with commit history. There's a lot of issues surrounding authentication using this plugin with no responses. Also last commit is like 3 months ago. Is this still being developed?

**Comment by r3kzi** [comment]
I was actually able to solve this by giving my EC2 instance profile the permission for ES

**Comment by AustinTag** [comment]
You are correct that access and secret keys apply to a specific IAM user/role for the domain access policy. We do not currently support AWS Cognito auth via this plugin. Please see the README for authentication options. 

If there is a feature request for using AWS Cognito, then please re-open this issue and we can mark this as a feature request.
