### ISSUE TITLE
Logstash logs a message about version 0.1.x when 0.2.0 is installed

### ISSUE THREAD

**Issue by dansmith65** [awslabs/logstash-output-amazon_es#16]
I'm running logstash version 2.1.1 on Windows Server 2012 with version 0.2.0 of this plugin, and get this message in the logstash log file (when --verbose option is used):

> Using version 0.1.x output plugin 'amazon_es'. This plugin isn't well supported by the community and likely has no maintainer.

My output config looks like this:

```
output {
	amazon_es {
		hosts => ["myurl.es.amazonaws.com"]
		region => "us-west-1"
		aws_access_key_id => '[MYID]'
		aws_secret_access_key => '[MYKEY]'
		index => "logstash-%{+YYYY.MM.dd}"
	}
}
```

**Comment by akhon** [comment]
having the same issue on centos, logstash version 2.2.2, amazon_es version 0.3

**Comment by malpani** [comment]
Thanks. This message comes from logstash for non 1.x versions. It is now gone since the release of 1.0 version. 
Source: https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html
> Version messaging from Logstash
> 
> If you start Logstash with the --verbose flag, you will see messages like these to indicate the relative maturity indicated by the plugin version number:
> 
>     0.1.x
> 
>     This plugin isn't well supported by the community and likely has no maintainer.
> 
>     0.9.x
> 
>     This plugin should work but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.
> 
>     1.x.x You will no longer see a message indicating potential code immaturity when a plugin reaches version 1.0.0
