### ISSUE TITLE
Missing 7.0.x Tags and changelog

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [awslabs/logstash-output-amazon_es#165]
There are two versions of this plugin released on ruby gems without corresponding tag and changelog here (7.0.0 and 7.0.1)

**Comment by dlvenable** [comment]
@SharpEdgeMarshall , I believe that the commit for these two versions is not available. So unfortunately, we cannot tag them. However, version 7.1.0 is the latest version and is tagged.
