### ISSUE TITLE
Support instance profiles?

### ISSUE THREAD

**Issue by jhovell** [awslabs/logstash-output-amazon_es#18]
I see in the README this is expected in the next release. Any idea when this release has expected? I haven't seen any activity here in a month or so...  Thanks!

**Comment by malpani** [comment]
This was addressed in #7 I will update the documentation to reflect the same

**Comment by jhovell** [comment]
Great, thank you! Works great...

**Comment by hairyhenderson** [comment]
@malpani - can you update the docs? I just spent a day under the assumption that this wasn't supported... :)

**Comment by jhovell** [comment]
@hairyhenderson https://github.com/awslabs/logstash-output-amazon_es/pull/22

**Comment by malpani** [comment]
@hairyhenderson Sorry about that. I hate when that happens to me. Have merged in #22 to reflect the same.

**Comment by hairyhenderson** [comment]
Thank you! :)
