### ISSUE TITLE
Unable to install plugin: "Can only install contrib at this time... Exiting"

### ISSUE THREAD

**Issue by romanr** [awslabs/logstash-output-amazon_es#19]
Unable to install on clean distribution of Debian Linux, following all the instructions:

1. Install logstash official package following the instrucitons at https://www.elastic.co/guide/en/logstash/current/package-repositories.html
3. cd to logstash directory:  ```cd /opt/logstash```
2. Run command as instructed: ```bin/plugin install logstash-output-amazon_es```

Output:
```Can only install contrib at this time... Exiting.```

How do I get this installed?

**Comment by jhovell** [comment]
@romanr I got that message When I tried to install on logstash 1.4. Are you positive you installed logstash 2?

**Comment by romanr** [comment]
oops, indeed it was wrong version!
