### ISSUE TITLE
Any help on role setup or instance profile?

### ISSUE THREAD

**Issue by romanr** [awslabs/logstash-output-amazon_es#20]
Can you please add documentation example snippet for role and/or instance profile setup in IAM?

**Comment by jhovell** [comment]
@romanr you just need to create a role and launch an EC2 instance using that role. Nothing ES specific.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

In the Amazon ES console 

http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-access-policies

Example access policy for ES (for us-west-2, but sub your region and other specifics in all caps):
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::YOUR_ACCOUNT_NO:role/YOUR_ROLE_NAME"
        ]
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:us-west-2:YOUR_ACCOUNT_NO:domain/YOUR_ES_DOMAIN/*"
    },
  ]
}
```

**Comment by malpani** [comment]
thanks @jhovell . @romanr hope you have not hit further issues with the plugin
