### ISSUE TITLE
Issue due manticore version

### ISSUE THREAD

**Issue by alex88** [awslabs/logstash-output-amazon_es#23]
Trying to install on latest logstash I get:

```
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "manticore":
In snapshot (Gemfile.lock):
manticore (= 0.5.2)
 
In Gemfile:
logstash-output-http (>= 0) java depends on
logstash-mixin-http_client (< 3.0.0, >= 2.2.0) java depends on
manticore (< 1.0.0, >= 0.5.2) java
 
logstash-output-http (>= 0) java depends on
logstash-mixin-http_client (< 3.0.0, >= 2.2.0) java depends on
manticore (< 1.0.0, >= 0.5.2) java
 
logstash-output-amazon_es (>= 0) java depends on
manticore (~> 0.4.2) java
```

maybe it's worth increasing the dependency version with manticore?

**Comment by amvapor** [comment]
Running into this as well

**Comment by alex88** [comment]
For everyone, just fix the logstash version to 2.1.1 instead of 2.1.2 and it'll be fixed for now

**Comment by henryturk** [comment]
2.2.x is the current supported version for package installations.

https://www.elastic.co/guide/en/logstash/current/package-repositories.html

**Comment by alex88** [comment]
@henryturk have you tried with 2.2.x? I think the issue is there as well

**Comment by henryturk** [comment]
@alex88 Stack is being rebuilt right now, I'll report back in a few minutes.

**Comment by henryturk** [comment]
@alex88 Incrementing the dependency got the plugin to install. But I haven't yet tested anything else.

**Comment by alex88** [comment]
@henryturk so without the increment of dependency it doesn't work on 2.2.x too?

**Comment by henryturk** [comment]
@alex88 Correct.

**Comment by malpani** [comment]
Thanks for raising this, I am increasing the dependency and testing it out

**Comment by alex88** [comment]
THanks @malpani
