### ISSUE TITLE
Possible to run local

### ISSUE THREAD

**Issue by pontusab** [awslabs/logstash-output-amazon_es#25]
We are using Logstash to add content to ES from DynamoDb using the Logstash plugin [logstash-input-dynamodb](https://github.com/awslabs/logstash-input-dynamodb) and it works great both local and in production, but we now want to sing our requests to ES using this plugin. But we can´t get it to work in local. First of we do not provide any credentials in local to the Logstash input dynamodb plugin. 

The error message: `Failed to install template: undefined method 'credentials'`.

Is it possible to run this from local without actual credentials?

**Comment by AustinTag** [comment]
Right now this is not possible, and we don't have plans to implement this.
