### ISSUE TITLE
Timeout Error using Amazon AWS Linux

### ISSUE THREAD

**Issue by mjallday** [awslabs/logstash-output-amazon_es#26]
I've got a set of machines that were running this plugin successfully until about ten days ago. The entire cluster now tells me it's timing out attempting to connect to the ES cluster. 

Here's what I've got so far:

- Opened up the access policy on the ES cluster to anyone (no auth required)
- Created a new ES cluster
- Verified I can curl the endpoint including creating and indexes and documents.
- Tried logstash 1.4 through 2.2
- Tried the logstash-output-amazon_es plugin in various versions (0.2, 0.3)
- `jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on OpenJDK 64-Bit Server VM 1.7.0_91-mockbuild_2015_10_27_19_01-b00 +jit [linux-amd64]`
- `logstash 2.2.2`

Here's the error that I'm getting, it appears very straight forward except for the fact that I cannot reproduce it outside of logstash:

```
Attempted to send a bulk request to Elasticsearch configured at '["https://search-fudge-lvxtdxfbo2acev3jktqqidmmxa.us-west-2.es.amazonaws.com:443"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["https://search-fudge-lvxtdxfbo2acev3jktqqidmmxa.us-west-2.es.amazonaws.com:443"], :region=>"us-west-2", :aws_access_key_id=>nil, :aws_secret_access_key=>nil, :transport_options=>{:request=>{:open_timeout=>20, :timeout=>60}, :proxy=>nil}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::AWS, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"Read timed out", :error_class=>"Faraday::TimeoutError", :backtrace=>nil, :level=>:error, :file=>"logstash/outputs/amazon_es.rb", :line=>"372", :method=>"flush"}
```

Any thoughts on how to begin troubleshooting this?

**Comment by mjallday** [comment]
Closing, attempted the same thing using fluentd and it's also getting the timeout. The issue is not with the plugin :/

**Comment by tom-jennings-axomic** [comment]
Hi,

I came across this trying to fix a similar issue.
`:message=>"Cannot get new connection from pool.", :class=>"Elasticsearch::Transport::Transport::Error", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:193:in `perform_request'",`

ElasticSearch would work for a bit but then stop ingesting data.

Old config which failed
```yml
output {
  elasticsearch {
    hosts => ["https://search-*.us-east-1.es.amazonaws.com"]
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}
```
Logstash tries to get a list of hosts from Elasticsearch but AWS's implementation has changed the format of the data returned. For more details on the specifics. https://forums.aws.amazon.com/thread.jspa?threadID=222600
https://discuss.elastic.co/t/elasitcsearch-ruby-raises-cannot-get-new-connection-from-pool-error/36252/11

The working config.
```yml
output
 {
  elasticsearch {
    hosts => ["https://search-*.us-east-1.es.amazonaws.com"]
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}
```

tomwj
