### ISSUE TITLE
ElasticsearchIllegalArgumentException[explicit index in bulk is not allowed]

### ISSUE THREAD

**Issue by snandam** [awslabs/logstash-output-amazon_es#32]
I'm getting error while trying to send data from logstash. I'm probably doing something silly. 

Created an aws es cluster with
```sh
"rest.action.multi.allow_explicit_index" = false
```

Logstash version : 2.3.2

Logstash config

```sh
input {

stdin {}

}

output {
  stdout
  {
    codec => rubydebug
  }

  amazon_es {
    hosts => ["foo.us-east-1.es.amazonaws.com:"]
    region => "us-east-1"
    aws_access_key_id => "ACCESS_KEY"
    aws_secret_access_key => "SECRET_KEY"
    index => "logs"
}


}
```
Output error 
https://gist.githubusercontent.com/snandam/8c935a678f7366aac2e76f12323ec4eb/raw/63d3dd542763d81e53990ad79ab78d3deb900b74/gistfile1.txt

Any help is appreciated.

**Comment by malpani** [comment]
You are right, the output plugin interferes with `"rest.action.multi.allow_explicit_index" = false`

Related discussions: 
https://github.com/elastic/elasticsearch/issues/7256 
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/374

**Comment by snandam** [comment]
Thanks. I'm able to get this working after changing the setting and running logstash within the VPC

**Comment by malpani** [comment]
@snandam That is good to hear. It will be useful if you could share the setting changes you had to make

**Comment by snandam** [comment]
Issue was fixed when I updated the below setting to true
``
"rest.action.multi.allow_explicit_index" = true
``
