### ISSUE TITLE
Difference between this plugin and the upstream elasticsearch plugin?

### ISSUE THREAD

**Issue by fiunchinho** [awslabs/logstash-output-amazon_es#4]
Hi! What's the main difference between this plugin and the standard elasticsearch output plugin, with the "http" protocol?

Thank you.

**Comment by malpani** [comment]
The main differences from logstash-output-elasticsearch plugin are
* AWS V4 Signing support
* Client - custom timeouts and default 
* Absence of sniffing and other features which might not be relevant to Amazon Elasticsearch Service as requests get load balanced

You can continue to use logstash-output-elasticsearch if the Amazon Elasticsearch domain access policy does not require signing (IP based access control) as described at http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-logstash
