### ISSUE TITLE
Allow support for Logstash v5

### ISSUE THREAD

**Issue by willfarrell** [awslabs/logstash-output-amazon_es#42]
Logstash is now `5.0.0-rc1`. Would be nice to start testing this out and be ready for the `5.0.0` release.

``` bash
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.0.pre.rc1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.0.pre.rc1) java

    logstash-output-amazon_es (= 1.0) java depends on
      logstash-core (< 3.0.0, >= 1.4.0) java

    logstash-core (>= 0) java
```

**Comment by waynetaylor** [comment]
Same here: 
[logstash@logstashloaderbilling-272c0930-172_20_22_35 logstash-output-amazon_es]$ /opt/logstash-5.0.0/bin/logstash-plugin install logstash-output-amazon_es-1.0.gem
Validating logstash-output-amazon_es-1.0.gem
Installing logstash-output-amazon_es
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.0)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.0) java

    logstash-output-amazon_es (= 1.0) java depends on
      logstash-core (< 3.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

**Comment by den-is** [comment]
+1
any approximation when this might be ready ?

**Comment by msfroh** [comment]
I just merged this in (along with an update to support newer versions of aws-sdk). 

@den-is, let us know if you run into any problems.

**Comment by den-is** [comment]
updated, works just fine atm
thanks!
