### ISSUE TITLE
Task based Roles are not supported

### ISSUE THREAD

**Issue by jrstarke** [awslabs/logstash-output-amazon_es#44]
I'm working on deploying a cluster with ECS. As part of this, I wanted to have the Logstash shipping agent performed once per instance. The ECS Documentation had a useful article on [Starting a Task at Container Instance Launch Time](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/start_task_at_launch.html). Unfortunately, it appears that the amazon_es output does not support task based role permissions, as when I start the container, it complains that the machine role does not have permission to perform ESHTTP* on the ElasticSearch Service Domain.

**Comment by jfuen10** [comment]
I'm running into the same issue, can someone confirm or deny whether roles for tasks should work?

**Comment by syutingtaro** [comment]
Hi, 
I also got this issue when I tried to deploy this plugin in my AWS ECS cluster. The task role did not have the permission to perform ESHttp* on my AWS Elasticsearch domain. Is there any idea that can make it work?

**Comment by AustinTag** [comment]
Closing this issue since it is a few years old. However, if you are still tracking this issue, can you please provide the access policy for your Amazon Elasticsearch domain? You may need to explicitly give access to your ECS task role rather than the account.
