### ISSUE TITLE
Template not installed by logstash-output-amazon_es

### ISSUE THREAD

**Issue by gabeno** [awslabs/logstash-output-amazon_es#47]
I am using [logstash-output-elasticsearch](https://github.com/logstash-plugins/logstash-output-elasticsearch) to ingest data into my local elasticsearch instance. I however have to do similar set up  on Amazon es so I am using [logstash-output-amazon_es](https://github.com/awslabs/logstash-output-amazon_es) plugin. I have extended my former configs (_logstash-output-elasticsearch_) with aws access and secret keys. The  other config params remain the same, thus:

__logstash.conf__
```bash
input {
    jdbc {
        jdbc_driver_library => '/opt/postgresql-9.4.1208.jar'
        jdbc_driver_class => 'org.postgresql.jdbc.driver'
        jdbc_connection_string => 'jdbc:postgresql://db.region.rds.amazonaws.com:5432/udb'
        jdbc_user => 'xxx'
        jdbc_password => 'xxx'
        statement_filepath => './sql.txt'
    }
}

output {
    amazon_es {
        hosts => ['xxx.region.es.amazonaws.com']
        region => 'region'
        aws_access_key_id => 'xxx'
        aws_secret_access_key => 'xxx'
        index => 'profile'
        document_type => 'profile'
        manage_template => true
        template => './template.json'
        template_name => 'profile'
        template_overwrite => true
        document_id => '%{id}'
    }
}
```

__template.json__
```bash
{
    "template": "profile*",
    "settings" : {
        "index.mapper.dynamic": false,
        "index" : { ... },
        "analysis": {
            "char_filter": { ... },
            "tokenizer": { ... },
            "filter": { ... },
            "analyzer": { ... }
        }
    },
    "mappings": {
        "profile": {
            "_all": { "enabled": false },
            "properties": {
                ...
            }
        }
    }
}
```

The data is indexed alright but not with my custom mappings in the ```template.json``` when using _amazon_es_ as output (template is installed with _elasticsearch_ as output). On further investigation, I see the two plugins both install template from the source code [here](https://github.com/awslabs/logstash-output-amazon_es/blob/master/lib/logstash/outputs/amazon_es.rb#L235) and [here](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/template_manager.rb#L29).

Their respective log messages are:

__amazon_es__:
```bash
Automatic template management enabled {:manage_template=>"true", :level=>:info}
Using mapping template {:template=>{"template"=>"profile*" ...
```

__elasticsearch__:
```bash
Using mapping template from {:path=>"./template.json", :level=>:info}
Attempting to install template {:manage_template=>{"template"=>"profile*", ...
```

My logstash version is _2.3.4_ and elasticsearch version is _2.3.2_. No compatibility issues based on [this](https://www.elastic.co/support/matrix#show_compatibility).

I need help to figure out what might be amiss.

**Comment by raulvc** [comment]
Sorry for bringing this back to life, have you found a workaround for using your custom template overriding default mappings?

**Comment by gabeno** [comment]
@raulvc Apparently, I figured that one has to create an index after installing the requisite mappings and templates. I successfully did this locally, however not tried it out yet on Amazon ES. I might have been lucky a couple of times while working locally before I eventually got the flow right.

I will therefore close this issue.
