### ISSUE TITLE
Does this plugin support document_id?

### ISSUE THREAD

**Issue by mrcasablr** [awslabs/logstash-output-amazon_es#78]
Just wondering if I could map id from data source to es document id ?
```
        document_id => "%{id}"
```

**Comment by djcrabhat** [comment]
There is a config value carved out for it

https://github.com/awslabs/logstash-output-amazon_es/blob/a34c29a82707d3a559fe3ba131df2a37328ad071/lib/logstash/outputs/amazon_es.rb#L96

and I do see it getting sprintf'ed 
https://github.com/awslabs/logstash-output-amazon_es/blob/a34c29a82707d3a559fe3ba131df2a37328ad071/lib/logstash/outputs/amazon_es.rb#L303

so, even though it's not mentioned in the readme, I bet it'll work.

**Comment by xyq164202** [comment]
Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature

**Comment by Luk3rson** [comment]
It works. E.g.
`	amazon_es {
		hosts => ["monitoring"]
		region => "eu-central-1"
		index => "cloudfront-logs-%{+YYYY.MM.dd}"
		document_id => "%{[x_edge_request_id]}"
		max_bulk_bytes => 9999999
		}
	}`
