### ISSUE TITLE
Will this work with an IAM role?

### ISSUE THREAD

**Issue by red8888** [awslabs/logstash-output-amazon_es#79]
I'm going to have logstash running on a ec2 host or ECS container that will have been assign the MY_ES_CLUSTER role.

The arn of the MY_ES_CLUSTER role will be granted access to the es cluster.

So my question is, when that container/server runs is this plugin smart enough to grab those credentials from the environment? I shouldn't have to specify them manually in this case right?
 

My the logstash server is going to assume an iam role that has been granted access to ES.

I can use the environment variable AWS_PROFILE=MYROLE to set the role

**Comment by xyq164202** [comment]
Hi red8888:
    Yes, plugin can grant ec2 credentials without any settings, just make sure in your ES setting console 
"Modify access policy" tag add your ec2 instance profile.
