### ISSUE TITLE
HTTPS support missing

### ISSUE THREAD

**Issue by tabletcorry** [awslabs/logstash-output-amazon_es#8]
It appears that this plugin does not support HTTPS at all?

While I like the features that this offers (AWS Signature), the lack of HTTPS support makes it largely unusable.

**Comment by IrlJidel** [comment]
+1

**Comment by stevetu21** [comment]
+1

**Comment by jensendw** [comment]
I have this working via the change documented here:

https://github.com/awslabs/logstash-output-amazon_es/pull/12

**Comment by malpani** [comment]
Thank you @jensendw and @marckysharky . I have merged in your changes. 0.2.0 is https enabled by default.
