### ISSUE TITLE
amazon_es amazones - Failed to install template: Failed to parse mapping [_default_]

### ISSUE THREAD

**Issue by sadaf2605** [awslabs/logstash-output-amazon_es#81]
I am using `amazon_es` plugin on my `logstash`. 

My logstash.conf looks like following:

    input {
        tcp {
        host => "0.0.0.0"
        port => 5959
        codec => json
      }
    }
    output {
        amazon_es {
            hosts => ["XXXXXXX.ap-south-1.es.amazonaws.com"]
            region => "ap-south-1"
            aws_access_key_id => "XXXXXXXXX"
            aws_secret_access_key => "XXXXXXXXXXXXX"
            index => "production-logs-%(YYYY-MM-dd)"
        }
    }

I have following error:

    [ERROR] 2018-04-17 12:03:59.056 [[main]-pipeline-manager] amazones - Failed to install template: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [@version]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: No handler for type [string] declared on field [@version]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [@version]"}},"status":400}

**Comment by annuh** [comment]
It's because this plugin uses an old template.

The fix is documented here: https://stackoverflow.com/a/48687996/1255553

```
You should try to add the index template yourself. Copy this ES 6.x template on your local file system and then add the template setting to your amazon_es output, it should work:

  amazon_es {
    hosts => ["search-xxxxx.eu-west-3.es.amazonaws.com"]
    region => "eu-west-3"
    aws_access_key_id => 'xxxxxxxxxxxxxxxxxxxxxx'
    aws_secret_access_key => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    index => "test-migrate"
    document_type => "data"
    template => '/path/to/template.json'
  }

```

**Comment by xyq164202** [comment]
Hi, we just release new version of our plugin which has the template management and support ES 6.x version , can you try the new code to see if it resolve your issues? Thanks. Here is the link https://github.com/awslabs/logstash-output-amazon_es

**Comment by annuh** [comment]
Yes, thanks! This new version also fixes the issue 👍
