### ISSUE TITLE
What version of logstash is supported ?

### ISSUE THREAD

**Issue by yair5124302** [awslabs/logstash-output-amazon_es#84]
According to this [issue](https://github.com/awslabs/logstash-output-amazon_es/issues/51) the plugin support logstash < 6.
Is this still valid ?
Do you have plans to support logstash 6.x ?

**Comment by siulcode** [comment]
Any w.i.p. on this one? It looks like it is not working for the latest 6.3.1 version. 

Getting two errors:
`[2018-08-08T16:04:33,858][ERROR][logstash.outputs.amazones] Failed to install template: undefined method `credentials' for nil:NilClass`

`[logstash.outputs.amazones] Attempted to send a bulk request to Elasticsearch configured at '["https://<AWS ES ENDPOINT>:443"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?`

**Comment by xyq164202** [comment]
Hi, we just release new version of our plugin which support the newest logstash, can you try the new code to see if it resolve your issues? Thanks

**Comment by crisidev** [comment]
Resolving in favor of https://github.com/awslabs/logstash-output-amazon_es/blob/master/README.md#compatibility
