### ISSUE TITLE
ERROR: Mixed source of plugins, you can't mix local `.gem` and remote gems

### ISSUE THREAD

**Issue by amzrahulch** [awslabs/logstash-output-amazon_es#86]
git cloned the files and tried installing the plugin as per the instructions and got below issue:

[ec2-user@ip- logstash-output-amazon_es]$ sudo /opt/logstash/bin/logstash-plugin install logstash-output-amazon_es-2.0.0.gem --verbose --no-verify
ERROR: Mixed source of plugins, you can't mix local `.gem` and remote gems

See: 'bin/logstash-plugin install --help'

Tried editing the Gemfile, added below lines :

gem "logstash-output-amazon_es", :path => '/home/ec2-user/logstash-output-amazon_es/'

That did not work either. Same error! checked for any existing plugins by that name but could not locate anything :

ls /opt/logstash/vendor/bundle/jruby/1.9/gems/ | grep 'amazon' returns no results

I am stuck at this point. Please help.

**Comment by xyq164202** [comment]
Please go to your Logstash directory and use this ：
bin/logstash-plugin install logstash-output-amazon_es

**Comment by crisidev** [comment]
Resolving the issue as using default logstash installation script fixes the problem.
