### ISSUE TITLE
No support for DLQ

### ISSUE THREAD

**Issue by Bashton-MattBuckland** [awslabs/logstash-output-amazon_es#87]
It appears there's no support for the Dead Letter Queue. So any events that fail to index as a result of a 400 or 404 are silently dropped.

**Comment by malpani** [comment]
Yes, we will be adding this shortly.

**Comment by xyq164202** [comment]
Hi, in the next release we will add support for DLQ

**Comment by burghategaurao** [comment]
@xyq164202 & @malpani Could you please share dates for next release?
