### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by avisual** [awslabs/logstash-output-amazon_es#90]
I am trying your plugin to insert, but this seems to fail silently, having run logstash with debug level I am seeing no response from  Elastic and no errors in the log. Any pointers gratefully received

**Comment by malpani** [comment]
Can you please share the logstash version? Usually the debug mode ends up logging the payloads (and errors) very verbosely

**Comment by avisual** [comment]
logstash-6.2.4

**Comment by avisual** [comment]
I found the issue, it the types are different, my mapping was using doc and logstash defaults to log then it fails silently
