### ISSUE TITLE
Support for ELK 6.3

### ISSUE THREAD

**Issue by mauriziod** [awslabs/logstash-output-amazon_es#92]
Hi, are you planning to support latest version of Elasticsearch service?
AWS announced recently the possibility of zero-downtime for version upgrade and I believe lots of people will decide to move from v5.x to v6.x.

**Comment by xyq164202** [comment]
Hi, we are working on the new version of this plugin and it will release soon. In the new version it will support latest version of Elasticsearch service for sure.
