### ISSUE TITLE
No support for dynamic index

### ISSUE THREAD

**Issue by burghategaurao** [awslabs/logstash-output-amazon_es#95]
We need to have index name dynamically based on input event which we receive. So in output amazon Es plugin we are using information from metadata. But its not working. instead its creating index with name [@metadata][_index]
 filter
      {
	if [Method] == "GET" {
	mutate { add_field => { "[@metadata][_index]" => "log-getindex" } }
	}
	else if [Method] == "POST" {
	mutate { add_field => { "[@metadata][_index]" => "log-getindex" } }
	}
        json{
                   source => "message"
        }
      }
          output
      {
          stdout { codec => rubydebug}
         amazon_es {
                hosts => ["XYZ"]
                index => "%{[@metadata][_index]}"
                manage_template => false
              }
        }

**Comment by crisidev** [comment]
I am closing this issue since all latest versions support dynamic indexing. Feel free to reopen it if things are still not right for you. Thanks :)
